### ISSUE TITLE
Safari "Bug" for Instructions: Selecting text longer than containing field causes page jump

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#114] opened 2016-03-16 15:57 UTC
So far, this appears to be limited to Safari (i.e., not an issue in Chrome):

In the multi-line text fields provided for Reporting Instructions, if the existing text scrolls below the default containing field size, then when we try to select that text, the page instantly jumps to the bottom. While some of us know that we can expand the field and thus prevent this jumping behavior, we suspect some users won't know this. Is there something that can be done about this?

**Comment by ecsion** [comment] 2016-04-20 17:13
closing -- cannot reproduce. Please reopen if this issue happens again.

**Closed by ecsion** 2016-04-20 17:13 UTC
