### ISSUE TITLE
CASG: Project Summary Import Button 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#765] opened 2017-07-10 20:41 UTC
Hi, 

I thought we had the "Import Data" option under the "Project Summary" tab? 
It seems like it's no longer an option since the button is not showing up?  
https://eseagrant2.ucsd.edu/index.php?module=RFPProposal&view=Detail&record=40082&mode=showMultiQuestionStem&QuestionId=40085&tab_label=Project%20Summary&tab_label=Project%20Summary 

Thanks,

Miho

**Comment by ecsion** [comment] 2017-07-11 19:43
Hi Miho, The import data button is only shown when:
(1) the proposal is accessed from PI dashboard  
(2) The Import has to be enabled on custom form
(3) There has to be pervious answers on another proposal that used the same form.

I am assuming you are accessing the link from the PI dashboard, so that condition is met.
However in looking into "Project Summary" custom form, the import has been disabled. Please enable it.

Once you enable it, you will then still need to have a proposal that has Project Summary form answered by the PI. If there is another proposal that meets #3, then please attach the  url link of the other proposal which has "project Summary" form. We will then debug this further.

**Comment by ecsion** [comment] 2017-07-20 13:15
Closing this issue. You can reopen if the issue is not fully resolved.

**Closed by ecsion** 2017-07-20 13:15 UTC
