### ISSUE TITLE
WSG: Searching by PI on Reports main page inconsistent

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#285] opened 2016-07-18 18:03 UTC
Deepak: we get inconsistent results when searching the main Reports page by various PIs. For example, we search for Cheney or Becker and it just hangs (see screenshot: progress indicator goes on for 20-30 seconds, then returns "Server not found"). We searched for Poe, however, and it returned results immediately.

<img width="1308" alt="screen shot 2016-07-18 at 10 57 18 am" src="https://cloud.githubusercontent.com/assets/17168836/16924977/d12976c4-4cd6-11e6-9716-9f1cd706267b.png">

**Comment by ecsion** [comment] 2016-08-22 13:18
We could not reproduce. Likely an internet glitch. Closing the issue for now, if it happens again, please reopen the issue.

**Closed by ecsion** 2016-08-22 13:18 UTC
