### ISSUE TITLE
WSG - Project summary custom form to talk to Project_Summary_Form.pdf download

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#668] opened 2017-04-14 21:22 UTC
For the full proposal stage, we ask for summaries of objectives/methodology/rationale. In years past, this information was display only on the Project_Summary_Form.pdf download, which WSG uses as a cover sheet. 

At this time, we have a draft custom form created, called "Full Proposal Project Summary" (http://esg.wsg.washington.edu/index.php?module=MultipartQuestionStem&view=Detail&record=33207&viewname=213&showList=RFP&show_retire=).  This information needs to appear on the bottom of the download (below all other data). 

This request is similar to that of having the Focus Area(s) and SG Classification(s) form talk to the project summary.

This needs to be functional for testing prior to our opening date which will be in late April.

**Comment by ecsion** [comment] 2017-04-17 15:11
When you add a custom form, you can provide meaning to entries via keys. We have added the appropriate keys. We are closing this issue, please reopen if the issue is not resolved.

**Closed by ecsion** 2017-04-17 15:11 UTC
