### ISSUE TITLE
WSG: RFP reports - Average Panel Scores

### ISSUE THREAD

**Issue by chelkahn** [ecsion/eSeaGrant-Client-Bug-Tracker#760] opened 2017-06-23 18:14 UTC
http://esg.wsg.washington.edu/index.php?module=RFP&view=Detail&mode=DownloadReport&record=34267&tab_label=RFP%20Reports

Issues with Full proposal Average Panel Scores (Excel Export)
doesn’t currently seem to be working because only 2.5 reviews and comments are coming out but 12 have been submitted and at least 8 have been “accepted”

No changes when I "unaccepted" the Gallagher review without comments.

**Comment by ecsion** [comment] 2017-07-11 14:58
Chelsea, The new reports are now available. Can you check if the issue you experienced earlier is still happening and let us know. Please provide a marked up screenshot if the issue is not fixed. This will help us to reproduce and better understand the issue you are having.

**Comment by ecsion** [comment] 2017-07-26 14:57
Closing this. Please reopen if this is still an issue.

**Closed by ecsion** 2017-07-26 14:57 UTC
