### ISSUE TITLE
RISG: RFP Not behaving as set up; Forms not showing to PI etc.

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1034] opened 2020-04-10 15:40 UTC
At this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=createPhase&record=111608&phaseid=111610&tab_label=RnVsbC1Qcm9wb3NhbA==&source=RFP
I have Narrative, NEPA, and Data Management Plan forms selected as show to PI, Project Summary and Focus Areas NOT selected for show to PI. 

At this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=111618&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==
You see that the PI does not see the forms that are selected and checked Show to PI.

When I log back in as ADMIN and check the RFP (first URL above), none of the boxes I had checked remain checked----they are not being saved for some reason. 

Please correct this. Due date for proposals to this RFP is April 28, so this must be corrected quickly, please. Thank you.

**Comment by alandesbonnet** [comment] 2020-04-10 15:58
Also, in same RFP,
At this URL:
https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTExNjE4&id=449
you see that the budget rates set by ADMIN are showing as 0.535 in all boxes, yet at this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&record=111608&mode=showDurations&tab_label=QnVkZ2V0IFNldHVw
you see that ADMIN has set the first 2 sets of rates as 0.46. 
Something is seriously amiss here and needs to be corrected. Thanks.

**Comment by alandesbonnet** [comment] 2020-04-10 16:27
The above is happening to any and every RFP I develop, so it appears to be system-wide for RISG and not just specific to an individual RFP.

**Comment by ecsion** [comment] 2020-04-11 13:09
Hi Alan, A bug got introduced in RISG from showing logic on the last update that we missed. The issue is now fixed.

**Comment by ecsion** [comment] 2020-04-11 13:18
> Also, in same RFP,
> At this URL:
> https://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=MTExNjE4&id=449
> you see that the budget rates set by ADMIN are showing as 0.535 in all boxes, yet at this URL:
> https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&record=111608&mode=showDurations&tab_label=QnVkZ2V0IFNldHVw
> you see that ADMIN has set the first 2 sets of rates as 0.46.
> Something is seriously amiss here and needs to be corrected. Thanks.

Alan, The rates in the admin link are the rtes that are used as default. You can however, change the rates in the budget sheet which appears like what you have done. If you change rates in budget sheet, they will not reflect back on the admin link, or may be I am missing something. Let's have a short phone call on Monday so I can understand the issue.

**Comment by alandesbonnet** [comment] 2020-04-11 13:28
Thank you, the forms are now showing for the PI. My mistake on the indirect rates, I wasn’t thinking…what else is new?!!

Alan

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment] 2020-04-11 14:03
Closing issue.

**Closed by ecsion** 2020-04-11 14:03 UTC
