### ISSUE TITLE
RFP does not output combined budget

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#983] opened 2019-06-19 16:24 UTC
From my understanding, during the 2018-2020 RFP, the eSG Budget function would create a year 1 and year 2 budget, then would combine them into a total budget labeled as "full". I looked over the options of the RFP and could not see an option to allow the system to automatically output a combined budget. I have attached three screenshots of how the system outputted the budget in 2018. Is this still an option? 
![Year 1](https://user-images.githubusercontent.com/44243756/59782994-c631c680-9284-11e9-8443-361f642dcec4.JPG)
![Year 2](https://user-images.githubusercontent.com/44243756/59782996-c631c680-9284-11e9-92d0-fd8ccb43b524.JPG)
![Total](https://user-images.githubusercontent.com/44243756/59782997-c631c680-9284-11e9-929e-162efe8a48fa.JPG)

**Comment by alandesbonnet** [comment] 2019-06-19 16:29
Not sure what you are asking, but the bottom 90-4 IS the combined form, it just doesn’t come out with a date range on it — you can add this in a PDF editor if so desired.
If this does not address your question, my apologies. Please clarify further. 

Alan Desbonnet
Assistant Director

**Comment by Drew-Casey** [comment] 2019-06-19 18:09
Hi Alan, 
This is an example from 2018 competition, not our current RFP. We would like to replicate the bottom form with our current RFP.

**Comment by alandesbonnet** [comment] 2019-06-19 19:14
For a more than 1 year budget the combined budget page should automatically be produced.  If not then contact Ecsion via GitHub. Hope this helps.

**Comment by ecsion** [comment] 2019-06-20 11:15
Hi Drew, We were unable to reproduce the issue you have reported. Please provide us the url link to the RFP that you are having trouble with. Also is it Pre-Proposal phase or Full Proposal Phase.

We can then troubleshoot it more easily and get this issue fixed by tomorrow.

**Comment by Drew-Casey** [comment] 2019-06-20 13:29
On our "Texas Sea Grant RFP 2020-2022" Full Proposal RFP, when we download the zip packet for a proposal, it contains the two budget documents (year 1 and year 2) that the PIs inputted but it doesn't combine them into a third document. In the 2018-2020 RFP process, eSeaGrant would produce that third combined budget. There is no singular url because all proposals are affected.

**Comment by pankaj-ecsion** [comment] 2019-06-25 14:00
Fixed. Please check.

**Comment by ecsion** [comment] 2019-07-01 20:56
Closing. If not fixed, please reopen.

**Closed by ecsion** 2019-07-01 20:56 UTC
Labels: Fixed- Please check
