### ISSUE TITLE
MDSG: Report showing closed to PI, Cannot enter data.

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#885] opened 2018-09-19 13:51 UTC
High priority.
We have a report showing up as "closed" so that the PI cannot enter data. However, the reporting description is listed as open. I look at the reports listed under that report call and this one (R/AQ-4) is listed as "closed" when I open it up; another (R/AQ-4a) is listed as open. So it doesn't appear to be the report call interface. I'm not aware of a way to close an individual report attached to a report call.

![image](https://user-images.githubusercontent.com/31412413/45757221-b727c600-bbd7-11e8-8d72-e9e4ef223c22.png)

Report:
https://eseagrant.mdsg.umd.edu/index.php?module=Reporting&view=Detail&record=102210&mode=showInstructions&tab_label=SW5zdHJ1Y3Rpb25z&tab_label=SW5zdHJ1Y3Rpb25z

![image](https://user-images.githubusercontent.com/31412413/45757418-2ac9d300-bbd8-11e8-9cc7-f96d26b286e8.png)

The PI is trying to submit this NOW for our upcoming deadline. Can someone quickly address this?

Mike

**Comment by ecsion** [comment] 2018-09-20 14:42
Mike, There is some bug which we have to trace which is taking us time. Meanwhile, we have put a work around so the report is now open and the PI can input the report.

**Comment by mra142** [comment] 2018-09-20 14:44
Ok. Thanks. I will notify the PI.

Mike

-- Sent from mobile

**Comment by ecsion** [comment] 2018-09-28 22:39
Closing this, please reopen if the issue is not fixed.

**Closed** 2018-09-28 22:39 UTC
