### ISSUE TITLE
Alaska: System email templates not validating

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1092] opened 2021-01-08 18:25 UTC
Some or all of the system email templates are not validating, even when no changes are made, with the following error message:
Alert!
Invalid tags used: $%EmailSignature%$

For example, this happens with: 
$SysTemplate1$
Welcome email to New User. Also Welcome email resend to new user or existing user.

**Comment by ecsion** [comment] 2021-01-11 19:22
Dave, We have made the updates so this issue should not longer be happening. If you still see an issue, please post the url where the issue is happening.

**Comment by ecsion** [comment] 2021-01-21 20:47
Closing this issue, Please reopen in case you still encounter any problems,

**Closed by ecsion** 2021-01-21 20:47 UTC
Labels: Fixed- Please check

**Comment by dpartee** [comment] 2021-02-12 23:57
Looks good so far, I'm not getting the validation error. Thanks!
