### ISSUE TITLE
MDSG: Priority -- document request letter lost. 

### ISSUE THREAD

**Issue by mra142** [ecsion/eSeaGrant-Client-Bug-Tracker#871] opened 2018-04-25 15:07 UTC
We had an issue this morning with a Request Letter being lost and voided from the system. It looks like the request was sent and something was uploaded, but the upload was lost and the record is no longer associated with the specific proposal.

https://eseagrant.mdsg.umd.edu/index.php?module=MultipartAnswers&view=Detail&record=5469

Just a hypothesis (and I don't know why this would be the problem): I am wondering if there is a conflict with the letter because the faculty PI submitted the proposal and used the same email address for the document request?

Proposal location: https://eseagrant.mdsg.umd.edu/index.php?module=RFPProposal&view=Detail&record=5398&mode=showProposalTitle&tab_label=Start%20Here&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ==

I'm going to ask for a resubmission of the doc request, but can you please look into this issue.

**Comment by ecsion** [comment] 2018-08-08 10:09
Could not reproduce. Closing this issue. If this happen again, please reopen this issue.

**Closed by ecsion** 2018-08-08 10:09 UTC
