### ISSUE TITLE
ORSG: Invite Only RFPs showing up for "uninvited" users

### ISSUE THREAD

**Issue by STI-ORSG** [ecsion/eSeaGrant-Client-Bug-Tracker#986] opened 2019-06-27 15:33 UTC
We currently have a few RFPs open by invite only; however, I noticed that they are all showing up users even if they have not been added to the "enable access" list. I initially noticed this in my test account, but had signed in as another user for a different reason and saw all the open RFPs available in their account as well (they had not been 'invited' to access these RFPs). I checked to ensure that all the RFPs are indeed by invite only and checked the "enable access" lists.

**Comment by ecsion** [comment] 2019-07-01 00:59
We are unable to reproduce this issue. Could you please provide user name who is able to view a invite only rfp when he/she is not on the invite list.

**Comment by STI-ORSG** [comment] 2019-07-01 17:50
Thanks for your response. Logging in again this morning, it appears that the issue is resolved.

**Comment by ecsion** [comment] 2019-07-01 20:55
Ok, If you encounter this issue again, please reopen this issue and provide the url link, user name and a screenshot of the page and we will take a deeper dive into the issue. 

Closing this for now.

**Closed by ecsion** 2019-07-01 20:55 UTC
Labels: Clarification Needed
