### ISSUE TITLE
TXSG: Report Calls Randomly Drop Forms

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1066] opened 2020-07-29 15:52 UTC
Two report calls have randomly dropped all the selected custom forms since they were published. I checked them with a dummy PI account and they were working (as in, all the forms I wanted were visible to the PIs). I got emails from people on those two report calls that no forms were visible, so I had to re-check the custom forms.

Here are the two forms:
1. https://eseagrant.texasseagrant.org/index.php?module=CallReporting&view=Detail&record=127768&mode=linkCustomForms&tab_label=Link%20Custom%20Forms
2. https://eseagrant.texasseagrant.org/index.php?module=CallReporting&view=Detail&record=127985&mode=linkCustomForms&tab_label=Link%20Custom%20Forms

EDIT: I mean the "Show to PIs" checkboxes (flags) on the "Link Custom Forms" have become unchecked at some point after it was tested with a dummy PI/Project assigned to that report call. I have selected the forms and they are visible to PIs now. 

![image](https://user-images.githubusercontent.com/44243756/88828511-f5f21400-d190-11ea-83e6-d18e22af6d89.png)

**Comment by ecsion** [comment] 2020-08-05 16:21
Unable to reproduce this issue.

**Comment by Drew-Casey** [comment] 2020-08-05 17:38
I will keep an eye out for the next occurrence of this error. Please keep this open for a little while.

**Comment by ecsion** [comment] 2020-09-18 13:13
Closing. Please reopen if this issue happens again.

**Closed by ecsion** 2020-09-18 13:13 UTC
Labels: Unable to reproduce
