### ISSUE TITLE
PI Could Not Complete Form Questions

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1008] opened 2020-01-16 18:01 UTC
PI (Mary Wicksten) could not complete RQP-2019-Q4 report call for project 2014SP-R-Wickst-H10. 
The user said, "I can see all of the form but I cannot type anything in the fields." 
I logged in as the user and could enter data and save with no difficulties. I am not sure what is causing the problem.

Additionally, while logged in as the user, I noticed under the report call information that the due date was "0000-00-00 00:00:00" but there is no issue in the report call set up.

**Comment by ecsion** [comment] 2020-01-17 06:11
Hi Drew, We tried on our end and were not able to reproduce this issue. To troubleshoot further, please have Mary do the following:
1. send us the url link where she is having the issue. 
2. Have her send us a screen shot of the screen where the issue is happening
3. Have her send type of computer (Mac or pc), browser she is using (safari, chrome, firefox), browser version.

We will then try to troubleshoot and reproduce the issue.

**Comment by Drew-Casey** [comment] 2020-01-17 18:16
1.	The url we are focused on is http://eseagrant.texasseagrant.org/index.php?module=Reporting&view=Detail&record=120487&mode=showProjectInfo&tab_label=UHJvamVjdCBJbmZv&tab_label=UHJvamVjdCBJbmZv however nowhere in the form is it possible to fill in or change information
2.	Attached
3.	We have tried this form on a Mac and window 10 machine on Firefox, Safari, and Chrome, all at the latest versions.
![Screen Shot 2020-01-17 at 9 34 09 AM](https://user-images.githubusercontent.com/44243756/72635765-3855b100-3923-11ea-975b-b2d1d781422b.png)

**Comment by alandesbonnet** [comment] 2020-01-17 18:42
Drew

To change the Project Info you need to go into the Projects module and access that proposal. THEN you can edit those data. When in the Reporting module, you can only do reporting stuff, not change project level info. 
Hope this helps.

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment] 2020-01-22 01:57
Drew, Closing this issue, please reopen if not fixed.

**Closed by ecsion** 2020-01-22 01:57 UTC
Labels: Need more info - please see comments.
