### ISSUE TITLE
Alaska: "Click here" not ADA compliant, need alternative option for system email

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1095] opened 2021-01-08 20:23 UTC
The system email template for fellowship letter of recommendation request includes $#tasklink#$ which has the non-ADA-compliant “CLICK HERE” as the link text. I understand why generic text is used, but we must follow federal accessibility guidelines. Two possible solutions (I think #1 would be better):

1. Create a new variable for **letter writing task** that includes link text appropriate for _this particular task_ , e.g., $#lettertasklink#$ that would insert the custom link, along with the hyperlinked text "submit your letter of support in eSeaGrant" instead of "CLICK HERE".
2. Or, create a new variable for just the underlying task URL (for example $#taskurl#$), which would let me customize the text around it.

![image](https://user-images.githubusercontent.com/61889985/104060776-e5b07d00-51a3-11eb-8703-1792571de42d.png)

**Comment by ecsion** [comment] 2021-01-11 19:27
This is in progress. We are creating a link as you suggested.

**Comment by ecsion** [comment] 2021-01-21 20:47
We have added a field for the url and you can now modify the template as per your requirements. Please check.

**Comment by ecsion** [comment] 2021-02-12 15:18
Closing. If the issue is not fixed, please reopen.

**Closed by ecsion** 2021-02-12 15:18 UTC
Labels: Done. Please Check.

**Comment by dpartee** [comment] 2021-02-12 23:11
OK, that'll work, thanks. The variable you added, $#lettertasklink#$, is just the URL. Since the letter templates don't allow me to code HTML into the letter, I'm not able to use that variable to create an underlying link in an **a href** tag, and it won't let me put in a variable as the destination using the "link" tool. So my only option is to **visibly print that URL**, but I'm OK with that in this situation:  
![image](https://user-images.githubusercontent.com/61889985/107832102-0720fd80-6d3c-11eb-8402-0663496169c5.png)
