### ISSUE TITLE
Alaska: 'Choose file' button doesn't do anything

### ISSUE THREAD

**Issue by dpartee** [ecsion/eSeaGrant-Client-Bug-Tracker#1093] opened 2021-01-08 19:11 UTC
When trying to import custom forms via a JSON file: clicking on the “Select file” button doesn’t do anything in Safari 14.0.2. It works fine in Chrome and Firefox.
![image](https://user-images.githubusercontent.com/61889985/104054423-86e60600-5199-11eb-9426-8b1d021d1c95.png)
![image](https://user-images.githubusercontent.com/61889985/104054484-aed56980-5199-11eb-95dd-ce5d3bd44e8b.png)
![image](https://user-images.githubusercontent.com/61889985/104054555-cdd3fb80-5199-11eb-80ad-054a96dd158e.png)
![image](https://user-images.githubusercontent.com/61889985/104054590-d9bfbd80-5199-11eb-8970-f669b1542090.png)

**Comment by dpartee** [comment] 2021-01-08 23:27
The "select file" button not doing anything is also happening in other instances, such as trying to attach/upload a document as a letter-of-recommendation writer to a fellowship application.

**Comment by ecsion** [comment] 2021-01-11 19:26
We were not able to reproduce the you have reported. It would be helpful if you could take a video of the interaction, upload to google drive or dropbox and post a link here.

**Comment by ecsion** [comment] 2021-01-21 20:49
Could you please try again and see if this issue is still happening on your side. Thanks

**Comment by ecsion** [comment] 2021-02-12 15:18
Closing, If this issue is not fixed, please reopen.

**Closed by ecsion** 2021-02-12 15:18 UTC
Labels: Unable to reproduce

**Comment by dpartee** [comment] 2021-02-13 00:14
This issue did persist for me over an extended period of time (only in Safari). I just retried it, and the "file upload" seems to be working correctly now in my Safari, so all is good!
