### ISSUE TITLE
RISG -- Incorrect Travel Expense automatically inserted into new budget worksheet

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#547] opened 2017-01-26 14:35 UTC
At the following URL, upon creation of a new budget worksheet, the Travel expense of "ICES 2015 Conference" is automatically inserted upon worksheet creation. This must be corrected as this should not happen. All budgets will be WRONG until this is fixed. Thank You.

http://eseagrant.gso.uri.edu/operations.php?action=budget&proposal_id=NjIzMQ==&id=150

![screen shot 2017-01-26 at 9 31 31 am](https://cloud.githubusercontent.com/assets/18398763/22334983/c72ba302-e3aa-11e6-8c42-067e65190400.png)

**Comment by ecsion** [comment] 2017-01-27 13:56
Alan, there was an data issue with new budget sheet record creation for RI. We have fixed that. I am closing  this issue. In case you find the issue is not fixed or if this happens again, let me know and also open a new issue in Github.

**Closed by ecsion** 2017-01-27 13:56 UTC
