### ISSUE TITLE
RISG: PDF Proposal Creator NOT Functioning Properly

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#1074] opened 2020-09-17 14:26 UTC
At this URL:
https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=112057&phaseid=112059&tab_label=RnVsbC1Qcm9wb3NhbA==&showList=RFP#

This list of files to be used in creating the final proposal PDF are to be arranged as shown. However the 3rd document (Federal Partner Letter) is inserted as the 2nd document in the final PDF, not the 3rd as directed. ALSO, the 5th document listed (NEPA Questionnaire) does not load into the PDF that is created, despite that if I click to Preview the document, it downloads correctly by itself.

Please correct these 2 faults in the PDF proposal creator function as they cause incorrect documents to be created.
Thank You.

**Comment by Dipali-Ecsion** [comment] 2020-09-18 15:48
Fixed. Please check.

**Comment by alandesbonnet** [comment] 2020-09-18 16:03
The file is now created properly. However, when a user opens the file then tries to save it locally, (e.g., from this URL:  https://eseagrant.gso.uri.edu/index.php?module=RFP&view=Detail&mode=uploadProposalPdf&record=112057&phaseid=112059&tab_label=RnVsbC1Qcm9wb3NhbA==&showList=) then Acrobat hangs up at the screen shot below:

<img width="518" alt="Screen Shot 2020-09-18 at 11 56 04 AM" src="https://user-images.githubusercontent.com/18398763/93619566-bb457480-f9a6-11ea-8fa6-ed9096d2ae92.png">

Therefore, the reviewer (or ADMIN if they want to save the file elsewhere) is not able to save the PDF. Something in the file is not be happily recognized by Acrobat. If this can be corrected it will help tremendously.

**Comment by ecsion** [comment] 2020-12-20 16:06
Alan, we were not able to reproduce this issue. Could you please send us step by step instructions on how to reproduce.

**Comment by ecsion** [comment] 2021-01-07 20:09
Alan, we are closing this issue. If this reoccurs, please reopen or log a new issue.

**Closed by ecsion** 2021-01-07 20:09 UTC
Labels: Unable to reproduce
