### ISSUE TITLE
RISG -- Can't upload Publication PDF after saving publication data entry

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#702] opened 2017-05-01 12:13 UTC
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=5272&mode=showMultiQuestionStem&QuestionId=5114&tab_label=Publications&tab_label=Publications

logged in as the PI, publication information has been entered and saved. The PI then returns to the record with the PDF ready to attach, but cannot unless they delete the record and begin anew, which is not a useful way to work. Please correct this so that PIs can attach PDF after saving a record. Thank you.

**Comment by ecsion** [comment] 2017-05-01 15:23
Alan, The user **is** able to load the publication file without deleting the answer record.We believe what Dennis Nixon may be having a problem with is that if he has previously uploaded a file in an answer, he has to first delete the file and then upload another. This seems like the correct way to do it, since we only allow 1 file uploaded on a file upload question.

There is no option to simply upload a new file which replaces the previously uploaded file.  

Could you please confirm with Dennis and let us know.

**Comment by alandesbonnet** [comment] 2017-05-01 15:30
Deepak,
	It appears to be working now, so I am not sure if something was done on your end to correct the issue. Prior to just now, there was no file attached as the new record had just been created and saved. Then, logging back in, the PI could not attach a file—there was a file name of “no file.pdf” or something like shown instead of the SELECT FILE button now visible. He did indeed try to delete the  “no file” file and was returned a response that the file does not exist. Hence my message to GitHub. 
	Again, the issue seems to be resolved at this point, whether from logging out and in a few times or something done on your end.
Alan

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment] 2017-05-01 15:49
Alan, We are closing this issue for now. If this issue happens again, or if you find a way to reproduce it,  please reopen or add a new issue to Github.

**Closed by ecsion** 2017-05-01 15:49 UTC
