### ISSUE TITLE
WISG - Report PDF does not show some content

### ISSUE THREAD

**Issue by tomxiong-aqua** [ecsion/eSeaGrant-Client-Bug-Tracker#1088] opened 2020-12-18 22:43 UTC
Not sure if it was something the PI input or if there is something wrong with how I setup the report, but when you hit the "PDF this page" button, the pdf returned is missing the "Principal findings and significance" field in the "WRI - Progress Report".

It looks like this is just happening on this report: https://edrop.aqua.wisc.edu/index.php?module=Reporting&view=Detail&record=119956&mode=showFullReport&tab_label=U3VibWlzc2lvbiBQcmV2aWV3&tab_label=U3VibWlzc2lvbiBQcmV2aWV3

It works correctly in the other report calls.

**Comment by ecsion** [comment] 2020-12-21 16:19
The issue is due to < and > characters being used in text. We are looking into how to handle this situation. As a work around we have changed the < to *less than* spelt out.  and > to "greater than" spelt out. This is a temporary workaround. We are working on a permanent fix.

**Comment by tomxiong-aqua** [comment] 2021-01-04 19:42
Another thing I just noticed, in the pdf, there are question marks (?) in the title, they should be dashes (-). See the screenshot of the pdf below.

<img width="728" alt="Screen Shot 2021-01-04 at 1 35 01 PM" src="https://user-images.githubusercontent.com/36545478/103572706-a4158e80-4e92-11eb-9f0d-8bc5b0c7ad8b.png">

**Comment by ecsion** [comment] 2021-01-07 20:07
This is fixed. Now < or > symbol will work fine.

**Comment by ecsion** [comment] 2021-01-11 19:28
Closing this issue. Please reopen if you encounter this issue again.

**Closed by ecsion** 2021-01-11 19:28 UTC
Labels: Fixed- Please check
